
scrape_configs:
  - job_name: 'Service_Discovery'
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        filters:
          -name: "tag:<ec2_instance_tag_name>"
           values: ["yes"]



# vi /etc/prometheus/prometheus.yml
  - job_name: 'BuildMachine'
 static_configs:
   - targets: ['172.50.45.45:9100']