- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: present

#- name: Start & Enable Nginx service
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes

# Recursively remove directory of /nginx/html
- name: Remove the default content that web server is serving.
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create a directory if it does not exsit >> /usr/share/nginx/html
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download the frontend content and Unarchive a file that needs to be downloaded
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy file to /etc/nginx/default.d/roboshop.conf
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: ReStart & Enable Nginx service
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
